### ISSUE TITLE
Documentation refers to things that don't exist

### ISSUE THREAD

**Issue by jvasile** [novalagung/go-eek#1]
The readme refers to `NewEek`, which doesn't appear to exist.  `New` does, though.

The example defines `VarA` and `VarB`, but then evaluates with just `A` and `B`.  Being consistent with `VarA` and `VarB` fixes that.

**Comment by novalagung** [comment]
@jvasile I just updated the doc.

sorry, it takes a while for me to resolve this issue. I didn't realize there is an issue report on this repo. anyway thanks!
